name: Bug Report
description: Create a report to help us improve Simen
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Please include screenshots if possible.
      placeholder: "When I do X, Y happens..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: "How can we reproduce the issue? Please provide a step-by-step guide."
      value: |
        1. 
        2. 
        3. 
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Simen Version
      description: What version of Simen are you running?
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false 